routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Route::get('/', function () {
    return view('welcome');
});
 */

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/cockpit', 'Admin\CockpitController@index')->name('cockpit');
Route::resource('/cockpit/posts', 'Admin\PostController');
Route::resource('/cockpit/pages', 'Admin\PageController');
Route::resource('/cockpit/categories', 'Admin\CategoryController');
Route::resource('/cockpit/tags', 'Admin\TagController');
Route::resource('/cockpit/menus', 'Admin\MenuController');
Route::resource('/cockpit/reportages', 'Admin\ReportageController');

Route::get('/','PagesController@accueil')->name('accueil');

/*Route::get('/', function () {
    return view('welcome');
});*/

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $guarded = [];

    public function posts(){
        return $this->belongsToMany(Post::class);
    }

    public function reportages(){
        return $this->belongsToMany(Reportage::class);
    }
}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{

    public function __construct() {
        $this->middleware('auth', ['except' => ['auto']]);
    }

    public function auto(Request $request){
        $term = $request->get('term');
        return Tag::select('title')->where('title', 'LIKE', $term.'%')
            ->get()
            ->map(function ($tag){
                return [
                    'id' => $tag->title,
                    'label' => $tag->title,
                    'value' => $tag->title
                ];
            });
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/tags/create.blade.php
@extends ('layouts.cockpit')

@section('content')
    <div class="row">
        <div class="col text-right">
            <a class="btn btn-warning" href="{{ route('posts.index') }}">Retour</a>
        </div>
    </div>
    <div class="row">
        <div class="col">
            @include('admin.posts.form',['action' => 'store'])
        </div>
    </div>
@endsection


@section('css')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
@endsection
@section('js')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script src="//cloud.tinymce.com/stable/tinymce.min.js?apiKey=40cakvroazrt9qmtcvc4jhwddimpi2cj26v8c03jxkfbc499"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="{{ asset('/js/editor.js') }}"></script>
@endsection

resources/views/admin/tags/edit.blade.php
@extends ('layouts.cockpit')

@section('content')
    <div class="row">
        <div class="col text-right">
            <a class="btn btn-warning" href="{{ route('posts.index') }}">Retour</a>
        </div>
    </div>
    <div class="row">
        <div class="col">
            @include('admin.posts.form', ['action' => 'update'])

        </div>
    </div>
@endsection


@section('css')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
@endsection
@section('js')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script src="//cloud.tinymce.com/stable/tinymce.min.js?apiKey=40cakvroazrt9qmtcvc4jhwddimpi2cj26v8c03jxkfbc499"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="{{ asset('/js/editor.js') }}"></script>
@endsection

resources/views/admin/tags/form.blade.php
@if($action=='store')
    <form action="{{ action('Admin\PostController@store') }}" method="POST">

        @else
            <form action="{{ action('Admin\PostController@update', $post) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                @endif

                {{ csrf_field() }}

                <div class="form-group row">
                    <label for="staticEmail" class="col-sm-2 col-form-label">Tags</label>
                    <div class="col-sm-10">
                        <select name="tag_id" id="" class="select2" style="width: 100%">
                            @foreach($tags as $tag)
                                <option value="{{ $tag->id }}">{{ $tag->title }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="staticEmail" class="col-sm-2 col-form-label">Titre</label>
                    <div class="col-sm-10">
                        <input type="text"  class="form-control" name="title" value="{{ old('title',$post->title) }}">
                    </div>
                </div>
                <div class="form-group row " style="display: none">
                    <label for="staticEmail" class="col-sm-2 col-form-label">Url</label>
                    <div class="col-sm-10">
                        <input type="text"  class="form-control" name="slug">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="staticEmail" class="col-sm-2 col-form-label" >Contenu</label>
                    <div class="col-sm-10">
                        <textarea class="editor" name="content" cols="30" rows="10">{{ old('content',$post->content) }}</textarea>
                    </div>
                </div>

                <button type="submit">Enregistrer</button>
            </form>

resources/views/admin/tags/index.blade.php
@extends ('layouts.cockpit')

@section('content')
    <div class="row">
        <div class="col">
            <a class="btn btn-primary" href="{{ route('posts.create') }}">Ajouter</a>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table">
                <tbody>
                @foreach($posts as $post)
                    <tr>
                        <td>
                            {{ $post->title }}
                        </td>
                        <td>
                            {{ $post->slug }}
                        </td>
                        <td>{{ $post->updated_at }}</td>
                        <td>
                            <a href="{{ route('posts.edit', $post) }}"  title="Editer l'article" class="blue>"><i class="fas fa-edit"></i></a>&nbsp;
                            <a href="{{ action('Admin\PostController@destroy', $post) }}" class="red" data-method="delete" data-confirm="Voulez-vous bien supprimer cet article"><i class="fas fa-trash-alt"></i></a>

                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection